---

- name: ensure authorized_keys_base_dir
  file:
    path: "{{ authorized_keys_base_dir }}"
    state: directory
    mode: 0755

- name: create user
  user:
    name: "{{ authorized_keys_user }}"
    password: '!'

- name: register userid
  command: id -u {{ authorized_keys_user }}
  register: uid1

- name: debug uid1
  debug:
    var: uid1.stdout

- name: configure SSH authorized_keys for {{ authorized_keys_user }}
  authorized_key:
    path: "{{ authorized_keys_base_dir }}/{{ authorized_keys_user }}/authorized_keys"
    user: "{{ authorized_keys_user }}"
    key: "{{ authorized_keys_key }}"
    key_options: command="/usr/bin/sudo /usr/local/sbin/backup_client"
    manage_dir: no
    exclusive: yes

- name: register status of authorized_key file
  stat:
    path: "{{ authorized_keys_base_dir }}/{{ authorized_keys_user }}/authorized_keys"
  register: stat1

- name: debug stat1
  debug:
    var: stat1.stat.uid

- name: remove user
  user:
    name: "{{ authorized_keys_user }}"
    state: absent

- name: create interim user
  user:
    name: "{{ authorized_keys_user }}_xxx"
    password: '!'

- name: create user
  user:
    name: "{{ authorized_keys_user }}"
    password: '!'

- name: register userid
  command: id -u {{ authorized_keys_user }}
  register: uid2

- name: debug uid2
  debug:
    var: uid2.stdout

- name: configure SSH authorized_keys for {{ authorized_keys_user }}
  authorized_key:
    path: "{{ authorized_keys_base_dir }}/{{ authorized_keys_user }}/authorized_keys"
    user: "{{ authorized_keys_user }}"
    key: "{{ authorized_keys_key }}"
    key_options: command="/usr/bin/sudo /usr/local/sbin/backup_client"
    manage_dir: no
    exclusive: yes

- name: remove interim user
  user:
    name: "{{ authorized_keys_user }}_xxx"
    state: absent

- name: register status of authorized_key file
  stat:
    path: "{{ authorized_keys_base_dir }}/{{ authorized_keys_user }}/authorized_keys"
  register: stat2

- name: debug stat2 uid
  debug:
    var: stat2.stat.uid

- name: check uid match for user and authorized_key file
  assert:
    that: stat2.stat.uid == uid2.stdout
